AWSTemplateFormatVersion: '2010-09-09'
Description: CFT Stack to create IAM role, group, policy and users

Parameters:
   password:
      Type: String
      NoEcho: True 
Resources: 
  DevGroupCreation: 
    Type: AWS::IAM::Group
    Properties:
      GroupName: devGroup
      
  TestingGroupCreation: 
    Type: AWS::IAM::Group
    Properties:
      GroupName: testGroup

  devUserCreation:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: 
          Ref: password
      UserName: devUser
  testingUserCreation:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: 
          Ref: password
      UserName: testUser
  AddusersToDevGroup:
     Type: AWS::IAM::UserToGroupAddition
     Properties: 
       GroupName: !Ref DevGroupCreation
       Users: 
          - !Ref devUserCreation

  AddtestusertoTestingGroup:
     Type: AWS::IAM::UserToGroupAddition
     Properties: 
       GroupName: 
          Ref: TestingGroupCreation
       Users: 
          - !Ref testingUserCreation

  TestingRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
             Version: 2012-10-17
             Statement:
                - Effect: Allow
                  Principal:
                     Service:
                     - ec2.amazonaws.com
                  Action:
                     - 'sts:AssumeRole'
      ManagedPolicyArns: 
          - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      RoleName: devRole
  TestingRole2:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
             Version: 2012-10-17
             Statement:
                - Effect: Allow
                  Principal:
                     Service:
                     - ec2.amazonaws.com
                  Action:
                     - 'sts:AssumeRole'
      ManagedPolicyArns: 
          - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      RoleName: testingRole 
  s3bucketDevGroupPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
         Groups:
           - !Ref DevGroupCreation
         PolicyName: s3DevGroupPolicy
         PolicyDocument:
            Version: 2012-10-17
            Statement:
               - Effect: Allow
                 Action:
                    - 's3:ListBucket'                    
                 Resource: 'arn:aws:s3:::devgroup-bucket:*'   
               - Effect: Deny
                 Action:
                    - 's3:*'                    
                 Resource: 'arn:aws:s3:::testinggroup-bucket:*'  

  s3bucketTestingGroupPolicy:
      Type: 'AWS::IAM::Policy'
      Properties:
         PolicyName: s3TestingGroupPolicy
         PolicyDocument:
            Version: 2012-10-17
            Statement:
               - Effect: Allow
                 Action:
                    - 's3:ListBucket'                    
                 Resource: 'arn:aws:s3:::testinggroup-bucket:*'
               - Effect: Deny
                 Action:
                    - 's3:*'                    
                 Resource: 'arn:aws:s3:::devgroup-bucket:*'
         Groups:
           - !Ref TestingGroupCreation
Outputs:
  devGroup:
    Value: !Ref DevGroupCreation
     
  testingGroup:
    Value: !Ref TestingGroupCreation
  devUser:
     Value: !Ref devUserCreation
  testingUser:
     Value: !Ref testingUserCreation  
  devGroupPolicy:
     Value: !Ref s3bucketDevGroupPolicy
  testingGroupPolicy:
     Value: !Ref  s3bucketTestingGroupPolicy
